import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:smartbus/screens/splash_screen.dart';  // Fixed import
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Initialize shared_preferences
  final SharedPreferences prefs = await SharedPreferences.getInstance();
  runApp(MyApp(prefs: prefs));
}

class MyApp extends StatelessWidget {
  final SharedPreferences prefs;
  const MyApp({super.key, required this.prefs});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BusEase',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: 'Inter', // Set the default font
      ),
      home: const SplashScreen(), // Start with the Splash Screen
    );
  }
}